Add-Type -AssemblyName System.Drawing
$bitmap = New-Object System.Drawing.Bitmap(32, 32)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.Clear([System.Drawing.Color]::FromArgb(26, 26, 46))
$pen = New-Object System.Drawing.Pen([System.Drawing.Color]::FromArgb(233, 69, 96))
$graphics.DrawEllipse($pen, 4, 4, 24, 24)
$pen2 = New-Object System.Drawing.Pen([System.Drawing.Color]::FromArgb(233, 69, 96), 2)
$graphics.DrawLine($pen2, 22, 22, 14, 14)
$bitmap.Save("C:/Users/zheng/worksentry/src-tauri/icons/icon.ico", [System.Drawing.Imaging.ImageFormat]::Icon)
$bitmap.Dispose()
